### call endpoint valid date
GET http://localhost:7071/api/token_balances?date=2025-12-12
Content-Type: application/json

### call endpoint - needs to default to using env variable for block_to
GET http://localhost:7071/api/token_balances
Content-Type: application/json

### call endpoint - invalid date only
GET http://localhost:7071/api/token_balances?date=2025-10-15
Content-Type: application/json
